### ISSUE TITLE
aws_s3_bucket_versioning with mfa_delete needs status = Enabled

### ISSUE THREAD

**Issue by danielcompton** [minamijoyo/tfedit#48]
```tf
resource "aws_s3_bucket" "global_cloudtrail_logs" {
  bucket        = "cloudtrail-logs"

  versioning {
    mfa_delete = true
  }
}
```

Is translated to:

```tf
resource "aws_s3_bucket" "global_cloudtrail_logs" {
  bucket = "cloudtrail-logs"
}

resource "aws_s3_bucket_versioning" "global_cloudtrail_logs" {
  bucket = aws_s3_bucket.global_cloudtrail_logs.id

  versioning_configuration {
    mfa_delete = "Enabled"
  }
}
```

This isn't quite correct, it should also have status

```tf
resource "aws_s3_bucket_versioning" "whim_global_cloudtrail_logs" {
  bucket = aws_s3_bucket.whim_global_cloudtrail_logs.id

  versioning_configuration {
    status     = "Enabled"
    mfa_delete = "Enabled"
  }
}
```

Relates to #40

**Comment by minamijoyo** [comment]
Hi @danielcompton, Thank you for reporting this!

I believe `enabled = true` has already been translated to `status = “Enabled”`. Isn't it enough? If I remember correctly, the s3 mfa_delete feature also requires versioning, so I think your configuration in v3 is invalid. Please correct me if I’m wrong.

Or did you mean that: Even though `mfa_delete = true` without `enabled = true` is valid in v3, `mfa_delete = “Enabled”` without `status = "Enabled”` is invalid in v4"?  That is to say, v4 also fixed the missing validation bug.

**Comment by danielcompton** [comment]
> Even though mfa_delete = true without enabled = true is valid in v3, mfa_delete = “Enabled” without status = "Enabled” is invalid in v4"? That is to say, v4 also fixed the missing validation bug.

Yep, the config we had above for v3 (and even v4) was valid, but they fixed it when they split the resources. I didn't realise this was a problem of our config. 

I'll leave it with you on whether you consider this a bug to fix or not, I could see it either way.

**Comment by minamijoyo** [comment]
@danielcompton I initially thought about fixing it if possible, but it turns out it's not as simple as I expected, considering that mfa_delete is set to false or a variable reference. So I'm not going to fix it in tfedit as a bug in AWS provider v3, but thank you again for reporting this! It would much help anyone who hit the same problem 👍
